[package]
name = "spectradb-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["default"] }
napi-derive = "2"
spectradb-core = { path = "../spectradb-core" }
serde_json = "1"

[build-dependencies]
napi-build = "2"
