[package]
name = "spectradb-cli"
version = "0.1.0"
edition = "2021"

[features]
default = []
native = ["spectradb-core/native"]

[dependencies]
clap = { version = "4", features = ["derive"] }
rustyline = "14"
serde_json = "1"
spectradb-core = { path = "../spectradb-core" }
